print("This is a black string followed by number ", 123, " then boolean ", true, "\n");
printRed("This is a red string followed by number ", 123, " then boolean ", true, "\n");
printOrange("This is an orange string followed by number ", 123, " then boolean ", true, "\n");
printGreen("This is a green string followed by number ", 123, " then boolean ", true, "\n");
printBlue("This is a blue string followed by number ", 123, " then boolean ", true, "\n");
var boatObject = {type:"yacht", length:12, beam:6, draught:2.1};
print("Object printing: ", boatObject, "\n");
//printLog("Test print");
print("Have printed to log file too!\n");
scriptResult("Print tests completed OK");
