#define     PLUGIN_VERSION_DATE "2022:03:01"
#define     PLUGIN_VERSION_COMMENT ""
#define     USERGUIDES "\nhttps://github.com/antipole2/JavaScript_pi/blob/master/documentation/JavaScript_plugin_user_guide.pdf\nor\nhttps://github.com/antipole2/JavaScript_pi/blob/master/documentation/JavaScript_plugin_user_guide.epub\n\n"
#define     PLUGIN_FIRST_TIME_WELCOME "Welcome to the JavaScript plugin\n\nRun your first script by clicking on the run button above\n\nThe User Guide can be downloaded from here:\n"
#define     PLUGIN_UPDATE_WELCOME "Plugin has been updated.  Changes:\n* This output pane now scolls to keep the last output visible\n* Various bug fixes and stability improvements\n\nThe updated User Guide can be downloaded from here:\n"
